### ISSUE TITLE
Compatibility with Ubuntu 18.04

### ISSUE THREAD

**Issue by Genda1ph** [sous-chefs/rvm#375]
Hello, I stumbled upon dependency issue using this cookbook with Ubuntu 18.04.

For Debian and Ubuntu you install `libreadline6` and `libreadline6-dev`, however Ubuntu 18.04 doesn't have either of those packages, instead you should use `libreadline7` and `libreadline-dev` (yes, the one without version has major package version 7), additionally I needed `ruby-dev`, but this might be my local issue.

This dependency should be listed in `providers/ruby.rb` and is easily fixed, at least for 18.04, by adding a condition:

```
pkgs += %w{ libreadline6 libreadline6-dev } if node['platform_version'].to_f < 18.0
pkgs += %w{ libreadline7 libreadline-dev ruby-dev} if node['platform_version'].to_f > 18.0
```

This allowed my chef-client run to complete.
It would be great if you could add this small change under v0.9.5.

Thanks!

**Comment by fieldse** [comment]
This is somewhere upstream in the `install_rubies` method of chef_rvm_recipe_helpers.rb

```
Chef::Exceptions::Package                                                                                                                                                                 
    -------------------------                                                                                                                                                                 
    rvm_environment[ruby-2.3.1] (/root/chef-solo/cookbooks-2/rvm/providers/default_ruby.rb line 37) had an error: Chef::Exceptions::Package: rvm_ruby[ruby-2.3.1] (/root/chef-solo/cookbooks-2
/rvm/providers/environment.rb line 70) had an error: Chef::Exceptions::Package: apt_package[libreadline6] (/root/chef-solo/cookbooks-2/rvm/providers/ruby.rb line 174) had an error: Chef::Exc
eptions::Package: libreadline6 has no candidate in the apt-cache                                                                                                                              
                                                                                                                                                                                              
    Cookbook Trace:                                                                                                                                                                           
    ---------------                                                                                                                                                                           
    /root/chef-solo/cookbooks-2/rvm/providers/ruby.rb:176:in `block in install_ruby_dependencies'                                                                                             
    /root/chef-solo/cookbooks-2/rvm/providers/ruby.rb:173:in `each'                                                                                                                           
    /root/chef-solo/cookbooks-2/rvm/providers/ruby.rb:173:in `install_ruby_dependencies'                                                                                                      
    /root/chef-solo/cookbooks-2/rvm/providers/ruby.rb:45:in `block in class_from_file'                                                                                                        
    /root/chef-solo/cookbooks-2/rvm/providers/environment.rb:74:in `ruby_resource'                                                                                                            
    /root/chef-solo/cookbooks-2/rvm/providers/environment.rb:39:in `block in class_from_file'                                                                                                 
    /root/chef-solo/cookbooks-2/rvm/providers/default_ruby.rb:41:in `block in class_from_file
```

**Comment by Xorima** [comment]
So this cookbook needs to actually test modern operating systems which will catch this (and other issues I suspect), #398 has been raised for this, but if anyone is willing to help it would be greatly appreciated. 

Note: If you do want to help I am happy to guide and assist on anything people are unsure of
