### ISSUE TITLE
Error: cannot load such file -- rvm

### ISSUE THREAD

**Issue by uson1x** [sous-chefs/rvm#400]
## :ghost: Brief Description

When running `rvm::user_install` recipe via `knife solo`, an error pops up: `cannot load such file -- rvm`.

Am I doing something wrong with how the cookbook is supposed to be used?

## :pancakes: Cookbook version

Current master branch:
```
GIT
  remote: https://github.com/sous-chefs/rvm
  ref: 2dd1038f1c620ebf6dfe06f656bf902eaf40fd53
  sha: 2dd1038f1c620ebf6dfe06f656bf902eaf40fd53
  specs:
    rvm (0.10.1)
```
## :woman_cook:  Chef-Infra Version

`chef_version=15.8.23`
(also tried latest chef)

## :tophat: Platform details

Debian 8 VPS at Linode
`Linux debian 5.4.10-x86_64-linode132 #1 SMP PREEMPT Thu Jan 9 21:17:12 UTC 2020 x86_64 GNU/Linux`

## Steps To Reproduce

I'm using `rvm::user_install` recipe with this node configuration:
```
"rvm": {
    "user_installs": [
      {
        "user": "someusername",
        "rubies": ["2.6.3"]
      }
    ]
  }
```

## :heavy_plus_sign: Additional context

I've read https://github.com/sous-chefs/rvm/issues/324, but it doesn't propose any solution except updating the cookbook, which I did - using master now.

This is the related log output that I see:
```
================================================================================
Recipe Compile Error in /root/chef-solo/local-mode-cache/cache/cookbooks/rvm/recipes/user_install.rb
================================================================================

LoadError
---------
cannot load such file -- rvm

Cookbook Trace:
---------------
  /root/chef-solo/local-mode-cache/cache/cookbooks/rvm/recipes/default.rb:25:in `from_file'
  /root/chef-solo/local-mode-cache/cache/cookbooks/rvm/recipes/user_install.rb:20:in `from_file'

Relevant File Content:
----------------------
/root/chef-solo/local-mode-cache/cache/cookbooks/rvm/recipes/default.rb:

 18:  #
 19:
 20:  # install rvm api gem during chef compile phase
 21:  chef_gem 'rvm' do
 22:    action :install
 23:    version '>= 1.11.3.6'
 24:  end
 25>> require 'rvm'
 26:
 27:  create_rvm_shell_chef_wrapper
 28:  create_rvm_chef_user_environment
 29:
 30:  class Chef::Resource
 31:    # mix in #rvm_cmd_wrap helper into resources
 32:    include Chef::RVM::ShellHelpers
 33:  end
 34:

System Info:
------------
chef_version=15.8.23
platform=debian
platform_version=8
ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
program_name=/usr/bin/chef-solo
executable=/opt/chef/bin/chef-solo


Running handlers:
[2020-06-01T06:55:12+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-06-01T06:55:12+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 05 seconds
[2020-06-01T06:55:12+00:00] FATAL: Stacktrace dumped to /root/chef-solo/local-mode-cache/cache/chef-stacktrace.out
[2020-06-01T06:55:12+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-06-01T06:55:12+00:00] FATAL: LoadError: cannot load such file -- rvm
```

**Comment by poudelprakash** [comment]
Facing same error, @uson1x were you able to get past this?

**Comment by uson1x** [comment]
@poudelprakash Unfortunately, no. Had to roll back to my old chef version and old rvm cookbook.

**Comment by zedtux** [comment]
I'm facing that exact issue right now.

**Comment by zedtux** [comment]
@poudelprakash have you found any workaround for this issue ?

**Comment by poudelprakash** [comment]
@zedtux no
